name: 'Terraform Plan and Apply'

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    name: 'Terraform Plan Job'
    runs-on: ubuntu-latest 
    
    steps:
    
     # Checkout the repository to the GitHub Actions runner
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

 
    - name: Terraform Init
      run: terraform init

      #Generates an execution plan for Terraform

    - name: Terraform Generate Plan
      run: terraform plan -out=terraform.plan

      #Upload Plan file as an Artifact
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: terraform.plan
  
  terraform-apply:
    name: 'Terraform Plan Job'
    runs-on: ubuntu-latest 
    needs: terraform-plan

    steps:
    
     # Checkout the repository to the GitHub Actions runner
    - name: Checkout the repository
      uses: actions/checkout@v4

 
     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

 
    - name: Terraform Init
      run: terraform init

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan  # Replace with your artifact name
        path: .   # Specify the download path

    - name: Apply the Terraform plan
      run: terraform apply -auto-approve terraform.plan    



