name: 'Terraform Plan and Apply'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read  # Allows reading repository contents
  actions: read   # Allows reading GitHub Actions metadata

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    name: 'Terraform Plan Job'
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Generate Plan
      run: terraform plan -out=terraform.plan

    - name: List Files in Directory
      run: ls -lah

    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan
        path: terraform.plan
        if-no-files-found: ignore

  terraform-apply:
    name: 'Terraform Apply Job'
    runs-on: ubuntu-latest
    needs: terraform-plan

    steps: 
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: terraform-plan
        path: .
        

    - name: Apply the terraform plan
      run: terraform apply -auto-approve terraform.plan
      

